name: buildtest

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 4c-dependencies
  FOUR_C_DOCKER_DEPENDENCIES_HASH: 7a6ad12e

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gcc9_build:
    env:
      CMAKE_PRESET: docker
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ppraegla/4c-dependencies:latest
      options: --user root --env OMPI_ALLOW_RUN_AS_ROOT=1 --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    defaults:
      run:
        shell: bash
    steps:
      - run: echo ${{ github.repository }}
      # Due to a bug in runner action the variables $GITHUB_WORKSPACE and ${{ github.workspace }} are different inside a container. https://github.com/actions/runner/issues/2058
      # The repo gets cloned to `/__w/4C/4C` ($GITHUB_WORKSPACE) while ${{ github.workspace }} points to `/home/runner/work/4C/4C`.`
      # Use $GITHUB_WORKSPACE instead of ${{ github.workspace }}
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ env.CMAKE_PRESET }}
      - name: info
        run: |
          pwd; ls -l
      - uses: ./.github/actions/configure_4C
        with:
          cmake-preset: ${{ env.CMAKE_PRESET }}
          build-directory: ${{ github.workspace }}/build
          additional-cmake-flags: -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
      - uses: ./.github/actions/build_4C
        with:
          build-targets: full
          build-directory: ${{ github.workspace }}/build
      - name: Package build directory
        run: tar -cvf $GITHUB_WORKSPACE/4C_build.tar $GITHUB_WORKSPACE/build
      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: 4C-build
          path: |
            ${{ github.workspace }}/4C_build.tar
          retention-days: 1
  gcc9_test:
    needs: gcc9_build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ppraegla/4c-dependencies:latest
      options: --user root --env OMPI_ALLOW_RUN_AS_ROOT=1 --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    strategy:
      fail-fast: false
      matrix:
        test-chunk: ["0,199", "200,399", "400,599", "600,799", "800,999", "1000,1199", "1200,1399", "1400,1599",
          "1600,1799", "1800,1999", "2000,2199", "2200,2399", "2400,2599", "2600,2799", "2800,"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Setup developer environment for testing
        run: |
          cd $GITHUB_WORKSPACE
          git config --global --add safe.directory $GITHUB_WORKSPACE
          ./utilities/set_up_dev_env.sh
      - uses: actions/download-artifact@v4
        with:
          name: 4C-build
          path: ${{ github.workspace }}
      - name: Extract 4C build
        run: |
          tar -xvf $GITHUB_WORKSPACE/4C_build.tar -C /
      - name: Test
        run: |
          cd $GITHUB_WORKSPACE/build
          time ctest -I $TEST_CHUNK -j `nproc` --output-on-failure --output-junit $GITHUB_WORKSPACE/junit_test_summary.xml
        env:
          TEST_CHUNK: ${{ matrix.test-chunk }}
      - name: Upload test summary
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-summary-${{ matrix.test-chunk }}
          path: |
            junit_test_summary-${{ matrix.test-chunk }}.xml
          retention-days: 1
